<?php
namespace Jobs\Double;

use Jobs\CheckWeekly;

class WeeklyEmailIntegration extends CheckWeekly
{
    /**
     * @var Mail
     */
    public $mailer = null;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->mailer = new Mail();
    }

    public function perform()
    {
        $this->notifyExcess();
    }

}