version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cashtrack
      MYSQL_USER: cashtrack
      MYSQL_PASSWORD: cashtrack
    ports:
      - "3306:3306"
  web:
    build: .
    container_name: php_web
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
      - ./docker/apache.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
