

        <div class="left-menu-block">
            <h5>Operations</h5>
            <hr/>
            <a id="addTransactionLink" href="#addTransaction">Add Expense</a>
            <div id="addTransactionForm" class="add-transaction" >
            </div>

        </div>


        <div class="left-menu-block">
            <h5>Expenses</h5>

            <hr/>
            <div>
                <a id="transactionView" href="/">By Transactions</a>
            </div>

            <div>
                <a id="accountView" href="/" data-backbone="true">By Accounts</a>
            </div>
        </div>



        <div class="left-menu-block">
            <h5>Reports</h5>
            <hr/>
            <div>
                <a href="#report/lastweek" data-backbone="true">Last Week</a>
            </div>

            <div>
                <a  href="/report/lastweek">Last Week</a>
            </div>

            <div>
                <a  href="/report/thisweek">This Week</a>
            </div>

            <div>
                <a  href="/report/thismonth">This Month</a>
            </div>
            <br/>
            <div>
                <a  href="/report/weekly">Weekly</a>
            </div>

            <div>
                <a  href="/report/monthly">Monthly</a>
            </div>


            <div>
                <a  href="/report/yearly">Yearly</a>
            </div>
        </div>





        <div id="monthOperations" class="month-operations">



            <div class="Accounts">
                <table id="bufferList" class="table table-hover">
                </table>
            </div>

        </div>

