<?php



$javascripts = array(
    'js/module/account/collection.js',
    'js/cashapp.js',
    'js/cashapp/models.js',
    'js/cashapp/views.js',
    'js/module/navigation/NavigationYear.js',
);


$this -> headScript() -> setAllowArbitraryAttributes(true);
$this->headScript()->appendFile('js/vendor/require/require.js','text/javascript', ['data-main' => 'js/main']);
//
//foreach ($javascripts as $script) {
//    $this->headScript()->appendFile($this->basePath($script));
//}


?>

<?php include_once 'year_navigation.phtml'; ?>


<div id="nav-meta" class="row nav-meta darkgray">
</div>
<div class="row">

    <div id="formContainer" class="col-md-2 lightgray">
         <?php echo $this->render('application/cash_nav.phtml'); ?>
    </div>


    <div  class="col-md-10">

            <div id="app">
            </div>
    </div>


</div>
