<?php
$javascripts = array(
    'js/module/account/collection.js',
    'js/cashapp.js',
    'js/cashapp/models.js',
    'js/cashapp/views.js',
    'js/module/navigation/NavigationYear.js',
);

foreach ($javascripts as $script) {
    $this->headScript()->appendFile($this->basePath($script));
}
?>

<?php include_once 'year_navigation.phtml'; ?>



<div class="row">

    <div id="formContainer" class="col-md-2">
         <?php echo $this->render('application/cash_nav.phtml'); ?>
    </div>
    <div class="col-md-10">
            <div>
                <h5 class="left">Category View</h5>
            </div>
            <div>
                <table id="app" class="table table-hover"></table>
            </div>
    </div>


</div>
