<?php

$chartClass = null;

if (!isset($chart)) {
    $chart = null;
}
isset($report_title) or $report_title = "Weekly";

switch ($chart) {
    case 'month':
        $chartClass = 'Cash.Views.MonthBarChart';
        break;

    case 'year':
        $chartClass = 'Cash.Views.YearBarChart';
        break;

    default:
        $chartClass = 'Cash.Views.WeekBarChart';
        break;
}


$year = date('Y');

$javascripts = array(
    'js/vendor/d3.v3.min.js',
    'js/module/navigation/NavigationYear.js',
    'js/module/breakdown/view.js',

);

foreach ($javascripts as $script) {
    $this->headScript()->appendFile($this->basePath($script));
}
?>

<div class="row">
    <?php include_once 'year_navigation.phtml'; ?>
</div>

<div class="row">
        <div id="formContainer" class="col-md-2">
            <?php echo $this->render('application/cash_nav.phtml'); ?>
        </div>
        <div class="col-md-10">

            <div>
                <h5 class="left"><?php echo $report_title; ?></h5>
            </div>

            <div class="bar-chart-container">
                <script>


                    var breakdown = new <?php echo $chartClass?>();
                    breakdown.render(<?php echo $year;?>);

                    var loader = function(year){
                        breakdown.render(year);
                    };

                    (new Cash.Views.NavigationYearView({el:$('.pagination'), doOnYearChange:loader})).render();


                </script>
            </div>

    </div>
</div>