<?php


$javascripts = array(
    'js/vendor/d3.v3.min.js',
    'js/module/navigation/NavigationYear.js',
    'js/module/breakdown/view.js',

);


foreach ($javascripts as $script) {
    $this->headScript()->appendFile($this->basePath($script));
}

if (!isset($url)) {
    $url = "/api/breakdown/week/" . $this->year . "/" . $this->week;
}

isset($report_title) or $report_title = 'This week';

?>

<div class="row">
    <div id="formContainer" class="col-md-2">
        <?php echo $this->render('application/cash_nav.phtml'); ?>
    </div>

    <div class="col-md-10">
        <div>
            <h5 class="left"><?php echo $report_title; ?></h5>
        </div>
        <div class="bar-chart-container">
            <script>


                var chart = new Cash.Views.WeekCategoriesBarChart();

                chart.render('<?php echo $url; ?>');


            </script>
        </div>
    </div>
</div>