<?php


$javascripts = array(
    'js/vendor/d3.v3.min.js',
    'js/module/navigation/NavigationYear.js',
    'js/module/breakdown/view.js',

);


foreach ($javascripts as $script) {
    $this->headScript()->appendFile($this->basePath($script));
}

if (!isset($url)) {
$url = "/api/breakdown/week/".$this->year."/" . $this->week;
}


?>

<div class="row">
    <div class="col-md-12 bar-chart-container">
        <script>


            var chart = new Cash.Views.WeekCategoriesBarChart();

            chart.render('<?php echo $url; ?>');


        </script>

    </div>
</div>