<?php

$chartClass  = 'Cash.Views.WeekBarChart';

if (isset($chart)) {
    $chartClass = 'Cash.Views.MonthBarChart';
}

$year = date('Y');

$javascripts = array(
    'js/vendor/d3.v3.min.js',
    'js/module/reports/leads.js',
    'js/module/reports/bubbleview.js',
    'js/module/navigation/NavigationYear.js',
    'js/module/breakdown/view.js',

);

foreach ($javascripts as $script) {
    $this->headScript()->appendFile($this->basePath($script));
}
?>
<style>

    .bar {
        fill: steelblue;
    }

    .bar:hover {
        fill: brown;
    }

    .excessive {
        fill:darkred;
    }

    .excelent  {
        fill:darkgreen;
    }
    .over {
        fill:rgb(255, 187, 120);
    }
    .axis {
        font: 10px sans-serif;
    }

    .axis path,
    .axis line {
        fill: none;
        stroke: #000;
        shape-rendering: crispEdges;
    }

    .x.axis path {
        display: none;
    }

</style>
<div class="row">
    <?php include_once 'year_navigation.phtml'; ?>
</div>

<div class="row">
        <div class="col-md-12 week-container">
            <script>


                var breakdown = new <?php echo $chartClass?>();
                breakdown.render(<?php echo $year;?>);

                var loader = function(year){
                    breakdown.render(year);
                };

                (new Cash.Views.NavigationYearView({el:$('.pagination'), doOnYearChange:loader})).render();


            </script>

    </div>
</div>