

<?php echo $this->doctype(); ?>

<html lang="en" class="no-js">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>


        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
            ->prependStylesheet($this->basePath() . '/css/ui-lightness/jquery-ui-1.10.3.custom.css')
            ->prependStylesheet($this->basePath() . '/css/normalize.css')
                        ->prependStylesheet($this->basePath() . '/css/main.css')
                        ?>

        <!-- Scripts -->
        <?php

        $javascripts = array(
           'js/vendor/modernizr-2.6.2.min.js',
           'js/vendor/jquery-1.10.2.min.js',
           'js/vendor/jquery-ui-1.10.3.custom.min.js',
           'js/vendor/underscore-min.js',
           'js/vendor/backbone-min.js',
           'js/plugins.js',
           'js/models.js',
           'js/views.js',
           'js/main.js'
        );
        foreach ($javascripts as $script) {
            $this->headScript()->appendFile($this->basePath($script));
        }

        echo $this->headScript();

    ?>

    </head>
    <body>
    <!--[if lt IE 8]>
    <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->


    <ul class="nav nav-pills">
        <li class="active"><a href="#">Cashflow</a></li>
        <li><a href="#">Merchants</a></li>
        <li><a href="#">Accounts</a></li>
        <li><a href="#">Import</a></li>

    </ul>

    </nav>

        <div class="container">


            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>

    </body>
</html>
