

<?php echo $this->doctype(); ?>

<html lang="en" class="no-js">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>


        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
            ->prependStylesheet($this->basePath() . '/css/ui-lightness/jquery-ui-1.10.3.custom.css')
            ->prependStylesheet($this->basePath() . '/css/normalize.css')
            ->prependStylesheet($this->basePath() . '/css/main.css')
            ->prependStylesheet($this->basePath() . '/css/bar.css')
            ->prependStylesheet($this->basePath() . '/css/style.css')
                        ?>

        <!-- Scripts -->
        <?php

        $javascripts = array();

        foreach (array_reverse($javascripts) as $script) {
            $this->headScript()->prependFile($this->basePath($script));
        }

        echo $this->headScript();

    ?>

    </head>
    <body>

    <!--[if lt IE 8]>
    <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->


        <div class="container-fluid finance-app">

            <div class="row">
                <div class="col-md-12">
                    <?php
                    echo $this->navigation('navigation')->menu()->setUlClass('nav nav-pills');
                    ?>

                </div>
            </div>


            <?php echo $this->content; ?>
            <hr>

            <footer>

                <p>&copy; 2013 - <?php echo date('Y') ?> Cosmin Dordea. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>

    </body>
</html>
