<?php
$javascripts = array(
    'js/module/account/collection.js',
    'js/cashapp.js',
    'js/cashapp/models.js',
    'js/cashapp/views.js',
    'js/module/navigation/NavigationYear.js',
);

foreach ($javascripts as $script) {
    $this->headScript()->appendFile($this->basePath($script));
}
?>

<?php include_once 'year_navigation.phtml'; ?>



<div class="row left-navigation">

    <div id="formContainer" class="col-md-2">


        <a id="addTransactionLink" href="#addTransaction">Add Expense</a>

        <div id="addTransactionForm" class="add-transaction" >
         </div>

        <div>
            <a id="accountView" href="" data-backbone="true">Conturi</a>
        </div>
        <div>
            <a id="transactionView" href="">Operatii</a>
        </div>

        <script type="text/template" id="add-transaction-template">

            <form   class="form-horizontal" role="form">

                <div class="form-group">

                    <label for="idAccount">Account</label>
                    <select  id="idAccount" name="idAccount" class="form-control">
                    </select>
                </div>

                <div class="form-group">
                    <label for="datepicker">Date</label>
                    <input type="text"  class="form-control" name="datepicker" id="datepicker" value="<%= date %>" />
                </div>

                <div class="form-group">
                    <input type="text" name="amount" class="form-control" id="amount" placeholder="Amount" value="<%= amount %>">
                </div>
                <div class="form-group">

                    <textarea class="form-control" name="description" rows="3"><%= description %> </textarea>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">Add</button>
                    </div>
                </div>
            </form>
        </script>

        <div id="monthOperations" class="month-operations">



            <div class="Accounts">
                <table id="bufferList" class="table table-hover">
                </table>
            </div>

        </div>


    </div>
    <div class="col-md-10">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title left">Category View</h3>

            </div>
            <div class="panel-body">
                <table id="app" class="table table-hover"></table>
            </div>
        </div>
    </div>



</div>
