<?php
$javascripts = array(
    'js/cashapp.js',
    'js/cashapp/models.js',
    'js/cashapp/views.js',
);

foreach ($javascripts as $script) {
    $this->headScript()->appendFile($this->basePath($script));
}


?>

<div class="row">
    <ul class="pagination">
        <li><a href="#">&laquo;</a></li>
    </ul>
</div>



<div class="row left-navigation">
    <div id="formContainer" class="col-md-2">
        <div id="addTransactionForm" class="add-transaction" >
         </div>


        <div id="monthOperations" class="month-operations">

            <a id="addTransactionLink" href="#addTransaction">Add Expense</a>

            <div class="Accounts">
                <table id="bufferList" class="table table-hover">
                </table>
            </div>

            <div class="end-month">
                <button class="btb btn-primary">End Month</button>
            </div>
        </div>


    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title left">Category View</h3>

            </div>
            <div class="panel-body">
                <table id="app" class="table table-hover"></table>
            </div>
        </div>
    </div>
    <div class="col-md-1">

        <div>
            <div>
                <a id="accountView" href="" data-backbone="true">Conturi</a>
            </div>
            <div>
                <a id="transactionView" href="">Operatii</a>
            </div>


        </div>

    </div>

</div>
