<?php

$javascripts = array(
    'js/vendor/d3.v3.min.js',
    'js/reports/leads.js',
    'js/reports/bubbleview.js'
);

foreach ($javascripts as $script) {
    $this->headScript()->appendFile($this->basePath($script));
}
?>
<div class="merchants-container col-md-12">

    <script>
        var table  = d3.select("body .merchants-container").insert("table",":first-child")
            .attr("class","table table-hover");

        var thead = table.append('thead');
        var tbody = table.append('tbody');

        d3.json("/api/merchant" , function(error,data) {


            // append the header row
            thead.append("tr")
                .selectAll("th")
                .data(d3.keys(data[0]))
                .enter()
                .append("th")
                .text(function(column) { return column; });

            var rows = tbody.selectAll("tr")
                .data(data)
                .enter()
                .append("tr");

            var cells = rows.selectAll("td")
                .data(function(d){return d3.values(d);})
                .enter()
                .append("td")
                .text(function(d) {return d});

        });
    </script>
</div>