<?php

$this->headStyle()->appendStyle('/css/bootstrap-editable.css');

$javascripts = array(
    'js/vendor/d3.v3.min.js',
    'js/plugins/bootstrap-editable.js',
    'js/module/account/collection.js',
    'js/module/merchant/collection.js',
    'js/module/merchant/view.js',
);

foreach ($javascripts as $script) {
    $this->headScript()->appendFile($this->basePath($script));
}


?>
<div class="merchants-container col-md-12">

    <script>
        var view = new Cash.Views.Merchants();
    </script>
</div>